### ISSUE TITLE
Add backfill support in AthenaX

### ISSUE THREAD

**Issue by suez1224** [uber/AthenaX#12]

**Comment by HuangZhenQiu** [comment]
We are building end to end backfill solution for athenax in H2. We plan to open source it in Q1 2018.

**Comment by haohui** [comment]
That would be a great feature to have -- but I think it is a large feature that worth a more detailed discussion.

My feeling is that Github issue might not be the best place to start with. It is more for reporting bugs rather than identifying scopes, especially bigger ones like backfills.

Can you describe your design in a google doc and share it in the mailing list?
