### ISSUE TITLE
Some questions for test

### ISSUE THREAD

**Issue by kination** [uber/AthenaX#7]
Hello.
I have some questions while following up the document for quick start.
- It seems yarn need to be installed for working on. If it is right, how about adding on requirements in docs?
- I'm not sure how `localize.resources` and `additional.jars` are working. Could you explain more in detail, or update a sample?
- Is it okay to setup local file path of jar file if it is stored in local computer instead of hdfs path?
- I couldn't figure out the roll of `catalog.impl`

Sorry for lots of stuffs. Maybe it will be better if you could offer a clear sample for this.

Thanks.

**Comment by haohui** [comment]
I appreciate if you can move the questions to the mailing lists as you might get more help there.

1. Currently YARN is the only supported cluster management framework of AthenaX. Please feel free to file a PR to add it into the doc.
2. There are subtle differences between them and it would be great if you can come up with better names. Please see https://github.com/uber/AthenaX/blob/340e5ae12a014c0c81de8bcf36e78110c81f6375/athenax-backend/src/main/java/com/uber/athenax/backend/server/AthenaXConfiguration.java#L67 for detailed explanations.
3. You can put local paths in both `localize.resources` and `additional.jar` but YARN will copy the files over as the jars have to be physically available on the compute nodes in order to execute the job.
4. A catalog essentially describes how to map the tables in SQL to a real implementation (e.g. KafkaStream). Please see http://athenax.readthedocs.io/en/latest/design/#plugging-in-catalogs-and-connectors for more details. It might be helpful to provide an example that implement a catalog for a Kafka cluster, but unfortunately I don't have a lot of bandwidths these days. Your contributions are welcomed.

**Comment by kination** [comment]
@haohui Oh, I just find out google groups. I'll follow on there. Thanks.
